### ISSUE TITLE
Functions to incorporate for R training 

### ISSUE THREAD

**Issue by gcperk** [bcgov/Wetland_SkeenaESI_Monitoring#2]
List of functions to try to incorporate for data cleaning of wetland data sets: 
High priority: 
 - filter(), select(), group_by(), summarise() , mutate(),
Secondary: 
- ifelse(), gather() or spread() although I might save these for the demo/ 

I will be incorporating sf functions, st_intersect(), set_crs(), st_union() into the demo component

**Comment by DonMorgan** [comment]
Waiting for the gis stuff you are going to add?

**Comment by gcperk** [comment]
There is some components of the GIS in the script in the demo folder. 
I am happy to incorporate the GIS part if you can sort the data. I will create a branch and send you a pull request then you can merge to your script.
